### ISSUE TITLE
Jumping near top of Floor Boundary

### ISSUE THREAD

**Issue by Archimedyz** [Archimedyz/COMP_376_Project#1]
When Jumping near the top of the floor boundary, the player becomes stuck at the y-position.

Only occurs when Jumping occurs near the top.

**Comment by d-montalvo** [comment]
@Archimedyz When I synced the project the player gets set to a location of position Y= 0 when Idle in your scene with both our player class. Did something change?

**Comment by Archimedyz** [comment]
@d-Montalvo, 

@celcius112  seems to be having the same issues with my scene. He get's the player as unable to move. I have no Idea currently as to why this happens. 

I'm looking into it now.

**Comment by Archimedyz** [comment]
@d-montalvo 
I fixed the issue. It seems either myself or Lukas had added a keyframe in the idle animation that set the position to some absolute location. I removed the keyframe and all is good now.
