### ISSUE TITLE
Enemies going onto the tracks 

### ISSUE THREAD

**Issue by celcius112** [Archimedyz/COMP_376_Project#4]
Codewise, the hobo and neanderthal are not supposed to go into the tracks. SHould not be to hard to add this behaviour

**Comment by Robert-Anthony-Di-Monaco** [comment]
They now get killed if they're on the metro track. 

There's no need to allow the enemies to go onto track by themselves will make the level very easy.
And you can use the shurikens to teleport them on the track, like luring them into a trap.

**Comment by celcius112** [comment]
I wouldnt say its closed, cause the enemies shouldnt be able to come back to the regular floor. Also, theire layer should be updated if they are teleported to the metro floor

**Comment by Robert-Anthony-Di-Monaco** [comment]
Sure but the metros will kill them pretty quickly. We can alter it but it wont really make a difference.

**Comment by celcius112** [comment]
If they are teleported near the normal floor they will come back pretty quickly. I'll do it

**Comment by Robert-Anthony-Di-Monaco** [comment]
kk

**Comment by celcius112** [comment]
Enemy's layer changes accordingly. Don't go towards the player unless on same level.

**Comment by Robert-Anthony-Di-Monaco** [comment]
You forgot to push the changes.

**Comment by celcius112** [comment]
my bad I pulled but forgot tu push
